
#pragma once

#include <AzCore/Asset/AssetCommon.h>
#include <AzCore/Asset/AssetManagerBus.h>
#include <AzCore/Component/Component.h>
#include <AzCore/std/string/string.h>

#include <FoundationLocalisation/FoundationLocalisationBus.h>
#include <FoundationLocalisation/LexiconAssemblyAsset.h>

namespace FoundationLocalisation
{
    /**
     * TODO: Foundation for Localization (HeLex) Implementation
     * * CORE CONCEPT:
     * - A deterministic, flat-map "Resource Resolver" using xxHash64.
     * - Decouples logical addresses (Strings) from runtime values (Hashed IDs).
     * - Multi-Language: Each language is a separate 'LexiconAssemblyAsset' (.lexicon).
     *
     * 1. FILE TYPES & PIPELINE:
     * - .helex   (Source): Human-readable JSON <string "Path", string "Value/Uuid">.
     * - .lexicon (Product): Optimized Binary 'LexiconAssemblyAsset' (Serialized C++).
     * - DIGESTER (Asset Builder):
     * - Monitor .helex -> Generate .lexicon.
     * - Key Task: Hash "Path.To.Resource" into u64 keys.
     * - Key Task: Resolve UUID hex strings to binary AZ::Uuid and flag as
     * Product Dependencies to prevent asset stripping in builds.
     *
     * 2. RUNTIME ARCHITECTURE (LexiconAssemblyAsset):
     * - RECOMMENDED STRUCT: Contiguous memory block with a Sorted Index for O(log n) lookup.
     *
     *   {
     *       // We use a sorted vector for the fastest possible binary search/memory footprint
     *       struct Entry {
     *           uint64_t m_keyHash;     // xxHash64 of "Menu.Play"
     *           uint32_t m_dataOffset;  // Where the string/UUID is in the blob
     *           uint8_t  m_type;        // 0 = String, 1 = AssetId (Uuid)
     *       };
     *       AZStd::vector<Entry> m_index;
     *       AZStd::vector<uint8_t> m_bufferBlob; // The raw bytes for strings and Uuids
     *   };
     *
     * - ResourceVariant: Supports AZ::Uuid (AssetIds) or String (via String Pool/Blob).
     * - Resolution: L10nRequestBus handles global u64 -> Resource lookups.
     * - Swapping: Change languages by swapping the active LexiconAssemblyAsset.
     *
     * 3. DATA TYPES (LexiconText, LexiconSound, LexiconAsset):
     * - Tri-State Logic:
     * - Localized: Key-based lookup (Read-only in Inspector).
     * - Literal: Raw value entry (Standard behavior).
     * - Invariant: Flagged to be ignored by the Gatherer tool.
     * - Scripting: Reflect to BehaviorContext for Lua/Script Canvas.
     * - Console: Allow on-the-fly hashing of strings for live console debugging.
     *
     * 4. EDITOR UX (Qt / Property Handlers):
     * - HeathenPropertyHandler: Custom UI for Heathen types in Entity Inspector.
     * - Toggle Icon: Triggers menu to switch between Tri-states.
     * - Key Picker: TreeView overlay generated by tokenizing .helex keys by '.'.
     * - Gatherer Tool: Scraper to crawl Prefabs/Scripts for non-invariant literals
     * and batch-convert them into .helex entries.
     * - Script Canvas: Custom visualizers for L10n nodes to mirror Inspector UX.
     */
    
    class FoundationLocalisationSystemComponent
        : public AZ::Component
        , protected FoundationLocalisationRequestBus::Handler
        , public AZ::Data::AssetBus::MultiHandler
    {
    public:
        AZ_COMPONENT_DECL(FoundationLocalisationSystemComponent);

        static void Reflect(AZ::ReflectContext* context);

        static void GetProvidedServices(AZ::ComponentDescriptor::DependencyArrayType& provided);
        static void GetIncompatibleServices(AZ::ComponentDescriptor::DependencyArrayType& incompatible);
        static void GetRequiredServices(AZ::ComponentDescriptor::DependencyArrayType& required);
        static void GetDependentServices(AZ::ComponentDescriptor::DependencyArrayType& dependent);

        FoundationLocalisationSystemComponent();
        ~FoundationLocalisationSystemComponent();

    private:
        AZ::Data::Asset<Heathen::LexiconAssemblyAsset> m_activeAsset;
        AZ::Data::Asset<Heathen::LexiconAssemblyAsset> m_defaultAsset;
        AZStd::string m_activeCulture;
        AZStd::string m_defaultCulture;

        /// All lexicons loaded since Activate — used by GetAvailableLexiconIds().
        AZStd::vector<AZ::Data::Asset<Heathen::LexiconAssemblyAsset>> m_allLoadedAssets;

        /// Returns a pointer to the first loaded asset that services 'culture',
        /// or nullptr if none is found. Used for base-language fallback resolution.
        const Heathen::LexiconAssemblyAsset* FindAssetForCulture(const AZStd::string& culture) const;

    protected:
        ////////////////////////////////////////////////////////////////////////
        // FoundationLocalisationRequestBus interface implementation
        AZStd::string ResolveString(AZ::u64 key) override;
        AZStd::string ResolveString(const AZStd::string& path) override;
        AZ::Uuid      ResolveAssetId(AZ::u64 key) override;
        AZ::Uuid      ResolveAssetId(const AZStd::string& path) override;
        void          LoadCulture(const AZStd::string& cultureCode) override;
        void          UseCulture(const AZStd::string& cultureCode) override;
        AZStd::string GetActiveCulture() const override;
        void          SetDefaultCulture(const AZStd::string& cultureCode) override;
        AZStd::vector<AZStd::string> GetMappedCultureCodes() const override;
        AZStd::vector<AZStd::string> GetAvailableLexiconIds() const override;
        AZStd::string GetLexiconDisplayName(const AZStd::string& assetId) const override;
        LexiconHintType GetEntryHintType(AZ::u64 key) const override;
        ////////////////////////////////////////////////////////////////////////

        ////////////////////////////////////////////////////////////////////////
        // AZ::Data::AssetBus::MultiHandler
        void OnAssetReady(AZ::Data::Asset<AZ::Data::AssetData> asset) override;
        void OnAssetError(AZ::Data::Asset<AZ::Data::AssetData> asset) override;
        ////////////////////////////////////////////////////////////////////////

        ////////////////////////////////////////////////////////////////////////
        // AZ::Component interface implementation
        void Init() override;
        void Activate() override;
        void Deactivate() override;
        ////////////////////////////////////////////////////////////////////////

    };

} // namespace FoundationLocalisation
